[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chess"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.138.2",
    "pydantic>=2.13.4",
]

[tool.setuptools]
package-dir = {"" = "build"}
packages = ["libjupiter"]

[tool.setuptools.package-data]
libjupiter = ["*.so", "*.pyd"]

[tool.fastapi]
entrypoint = "server.main:app"

[tool.basedpyright]
extraPaths = ["./server"]
venvPath = "."
venv = ".venv"
