class TimeControl:
    seconds: int
    increment: int 

    def __init__(self, seconds: int, increment: int = 0):
        self.seconds = seconds
        self.increment = increment

class BaseEngine:
    def init(self, _tc: TimeControl, _fen: str | None = None) -> None:
        """ Initializes the engine.

        Params:
            tc: 
                Structure holding information about the time control.
                It is not required for this to affect your engine but 
                is provided as additional info.
            fen: 
                FEN representation of the initial state. If None then it 
                should be the starting position.

        The engine is expected to function in accordance with the rules, no 
        further validation is performed.
        """
        raise NotImplementedError("Please implement this method")

    def go(self, _ms_left: int) -> str:
        """ Searches for the best move given the amount of time left.

        Params:
            ms_left: 
                Remaining time to move in milliseconds.

        Returns: 
                The move it found in Long Algebraic Notation (LAN).

        The engine is expected to function in accordance with the rules, no 
        further validation is performed.
        """
        raise NotImplementedError("Please implement this method")

    def move(self, _move: str) -> None:
        """ Applies a move to the internal state of the engine.

        Params:
            move: 
                The move to make in Long Algebraic Notation (LAN)

        This move may or may not be generated by the engine. Internal state 
        should be updated accordingly.

        The engine is expected to function in accordance with the rules, no 
        further validation is performed.
        """
        raise NotImplementedError("Please implement this method")
