class TimeControl:
    seconds: float
    increment: float 

    def __init__(self, seconds: float, increment: float = 0.0):
        self.seconds = seconds
        self.increment = increment

class BaseEngine:
    def init(self, _tc: TimeControl, _fen: str | None = None) -> None:
        """ Initializes the engine.

        REQUIRED

        Params:
            tc: 
                Structure holding information about the time control. It is not 
                required for this to affect your engine but is provided as 
                additional info.
            fen: 
                FEN representation of the initial state. If None then it should 
                be the starting position. In FEN, knights are notated as 'n' and 
                kings are notated as 'k'.

        It is important that ALL engine state is reset on a call to init. A call 
        to init on a previously initialised engine instance should give the same 
        result as a call to init on a fresh instance.
        The engine is expected to function in accordance with the rules.
        """
        raise NotImplementedError("Please implement this method")

    def go(self, _ms_left: int) -> str | None:
        """ Searches for the best move given the amount of time left.

        REQUIRED

        Params:
            ms_left: 
                Remaining time to move in milliseconds.

        Returns: 
                The move it found in UCI-Flavoured LAN. Examples of this format
                are 'e2e4', 'e7e5', 'e1g1' (white short castling), 'e7e8q' (for 
                promotion.) Kings are notated as 'k' and knights as 'n'. Return 
                None if there are no legal moves.

        The engine is expected to function in accordance with the rules.
        """
        raise NotImplementedError("Please implement this method")

    def move(self, _move: str) -> None:
        """ Applies a move to the internal state of the engine.

        REQUIRED

        Params:
            move: 
                The move to make in UCI-Flavoured LAN. Examples of this format
                are 'e2e4', 'e7e5', 'e1g1' (white short castling), 'e7e8q' (for 
                promotion.) Kings are notated as 'k' and knights as 'n'.

        This move may or may not be generated by the engine. Internal state 
        should be updated accordingly.

        The engine is expected to function in accordance with the rules.
        """
        raise NotImplementedError("Please implement this method")

    def tuning_get_params(self) -> dict[str, float]:
        """ Returns a dictionary of named, tunable engine parameters.

        REQUIRED ONLY FOR TUNING

        Returns:
                A dictionary of named parameters and their corresponding values 
                as currently set within your engine. These are the parameters 
                that will be tuned. For example, you might return parameters  
                controlling your evaluation function. All values must be 
                normalised between -1.0 and 1.0 inclusive.

        To enable automatic engine tuning you must implement this method.
        """
        raise NotImplementedError("Please implement this method to enable tuning")

    def tuning_set_params(self, _params: dict[str, float]) -> None:
        """ Assign parameters from a dictionary to the engine.

        REQUIRED ONLY FOR TUNING

        Params:
            params: 
                A dictionary of named parameters and their corresponding values 
                to be passed to your engine. This will be called by the tuner 
                to change the behaviour of your engine to see which parameter 
                values are best. The names and types of the parameters will  
                exactly match the ones returned from `tuning_get_params`. All 
                params will be between -1.0 and 1.0 inclusive.

        To enable automatic engine tuning you must implement this method.
        """
        raise NotImplementedError("Please implement this method to enable tuning")

    def game_over(self) -> None:
        """ Called when the current game ends.

        NOT REQUIRED

        This is not a required method but is useful for printing out engine 
        metrics at the conclusion of the game.
        """
        pass

    def show(self) -> str:
        """ Used for debugging.

        NOT REQUIRED

        This is not a required method but is useful for printing out engine 
        state for debugging.
        """
        return repr(self)
