class TimeControl:
    seconds: int
    increment: int 

    def __init__(self, seconds: int, increment: int = 0):
        self.seconds = seconds
        self.increment = increment

class BaseEngine:
    def init(self, _tc: TimeControl, _fen: str | None = None) -> None:
        """ Initializes the engine.

        Params:
            tc: 
                Structure holding information about the time control. It is not 
                required for this to affect your engine but is provided as 
                additional info.
            fen: 
                FEN representation of the initial state. If None then it should 
                be the starting position. In FEN, knights are notated as 'n' and 
                kings are notated as 'k'.

        The engine is expected to function in accordance with the rules.
        """
        raise NotImplementedError("Please implement this method")

    def go(self, _ms_left: int) -> str:
        """ Searches for the best move given the amount of time left.

        Params:
            ms_left: 
                Remaining time to move in milliseconds.

        Returns: 
                The move it found in UCI-Flavoured LAN. Examples of this format
                are 'e2e4', 'e7e5', 'e1g1' (white short castling), 'e7e8q' (for 
                promotion.) Kings are notated as 'k' and knights as 'n'.

        The engine is expected to function in accordance with the rules.
        """
        raise NotImplementedError("Please implement this method")

    def move(self, _move: str) -> None:
        """ Applies a move to the internal state of the engine.

        Params:
            move: 
                The move to make in UCI-Flavoured LAN. Examples of this format
                are 'e2e4', 'e7e5', 'e1g1' (white short castling), 'e7e8q' (for 
                promotion.) Kings are notated as 'k' and knights as 'n'.

        This move may or may not be generated by the engine. Internal state 
        should be updated accordingly.

        The engine is expected to function in accordance with the rules.
        """
        raise NotImplementedError("Please implement this method")
